spring:
  application:
    name: HelmKubernetesTest1
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//localhost:1522/XEPDB1}
    username: ${SPRING_DATASOURCE_USERNAME:Transformer}
    password: ${SPRING_DATASOURCE_PASSWORD:transformer}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
  main:
    web-application-type: none
myapp:
  message: ${toPrint:default message}

#camel:
#  springboot:
#    main-run-controller: true




